<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Token');
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('app', 'Please continue the login process by writing the token generated by your authentication app:') ?></p>

    <?php $form = ActiveForm::begin([
        'id' => '2fa-token-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}\n{hint}</div>\n<div class=\"col-lg-8\">{error}</div>",
            //'labelOptions' => ['class' => 'col-lg-2 control-label'],
            'hintOptions' => ['class' => 'col-lg-12'],
        ],
    ]); ?>

        <?= $form->field($model, 'token')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'trust_user_agent')->checkBox() ?>

        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => '2fa-button']) ?>
            </div>

        </div>

    <?php ActiveForm::end(); ?>

</div>
