<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = Yii::t('app', 'Token');
$this->params['breadcrumbs'][] = $this->title;

$message = 'Please continue the login process by writing the token generated by your authentication app:';

if ($model->sms) {
    $message = 'Please continue the login process by writing the code received via SMS:';
    $this->title = Yii::t('app', 'Code');
}

$this->registerJs(
    "
    $('.loader').on('click', function(event){
        $('#loader').show();
    });
    ",
    \yii\web\View::POS_END,
    'loader_manager'
);

?>

<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if ($model->user->twoFactorAuthVerifiedViaSMS): ?>
        <p class="alert alert-warning"><?= Yii::t('app', 'You enabled two-factor authentication by having the token sent to you via SMS.'). ' ' . Yii::t('app', 'It is advisable to configure an authenticator app on your smartphone from your profile page; meanwhile, request a one-time code via SMS using the link at the bottom of this page.')  ?></p>
    <?php endif ?>

    <p><?= Yii::t('app', $message) ?></p>
    

    <?php $form = ActiveForm::begin([
        'id' => '2fa-token-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}\n{hint}</div>\n<div class=\"col-lg-8\">{error}</div>",
            //'labelOptions' => ['class' => 'col-lg-2 control-label'],
            'hintOptions' => ['class' => 'col-lg-12'],
        ],
    ]); ?>

    <?= $form->field($model, 'token')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'trust_user_agent')->checkBox() ?>

    <div class="form-group">
        <div class="col-lg-offset-3 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => '2fa-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <?php if(!$model->sms && $model->user->phone): ?>
    <hr>
    
    <?= Html::a(Yii::t('app', 'I cannot use the app: send me a code via SMS instead'), ['site/send-code-via-sms'], [
        'class'=>'btn btn-secondary loader', 
        'data' => [
            'confirm' => Yii::t('app', 'Please use this option only if the standard authenticator app does not work.'),
            'method' => 'post',
            ]
        ]) ?> <img style="display: none" id="loader" src="<?= Url::to('@web/images/submit_loader.gif') ?>" />
    <?php endif ?>

</div>
