<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = Yii::t('app', 'Two-factor authentication');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Profile'), 'url' => ['site/profile']];
$this->params['breadcrumbs'][] = $this->title;

$url = sprintf(Yii::$app->params['qrcode2fAUrl'], sprintf('otpauth://totp/%s (%s)?secret=%s', Yii::$app->name, Yii::$app->user->identity->username, $model->secret));

$this->registerJs(
    "
    $('.loader').on('click', function(event){
        $('#loader').show();
    });
    ",
    \yii\web\View::POS_END,
    'loader_manager'
);

?>

<div class="site-2fa">
    <h1><?= Html::encode($this->title) ?></h1>
    


    <?php $form = ActiveForm::begin([
        'id' => '2fa-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}\n{hint}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-2 control-label'],
            'hintOptions' => ['class' => 'col-lg-12'],
        ],
    ]); ?>

        <p>1. <?= Yii::t('app', 'In your authentication app scan this image, or type in the following code:') ?> <b><?= $model->secret ?></b></p>
        
        <p><img src="<?= $url ?>" /></p>

        <p>2. <?= Yii::t('app', 
            Yii::$app->session->get('2FA_secret_viasms', 0)==0
            ?
                'Finalize the process by writing the token generated by the authentication app:'
            :
                'Finalize the process by writing the token received via SMS:'
        ) ?></p>

        <?= $form->field($model, 'token')->textInput(['autofocus' => true]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton(Yii::t('app', 'Enable two-factor authentication'), ['class' => 'btn btn-primary', 'name' => '2fa-button']) ?>
            </div>

        </div>

    <?php ActiveForm::end(); ?>
    
    <hr>
    
    <?= Html::a(Yii::t('app', 'I cannot use the app: send me the token via SMS instead'), ['site/send-token-via-sms'], [
        'class'=>'btn btn-secondary loader', 
        'data' => [
            'confirm' => Yii::t('app', 'Please use this option only if the standard authenticator app does not work.'),
            'method' => 'post',
            ]
        ]) ?> <img style="display: none" id="loader" src="<?= Url::to('@web/images/submit_loader.gif') ?>" />
    
</div>
