<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Two-factor authentication');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Profile'), 'url' => ['site/profile']];
$this->params['breadcrumbs'][] = $this->title;

$url = sprintf(Yii::$app->params['qrcode2fAUrl'], sprintf('otpauth://totp/%s (%s)?secret=%s', Yii::$app->name, Yii::$app->user->identity->username, $model->secret));

?>

<div class="site-2fa">
    <h1><?= Html::encode($this->title) ?></h1>
    


    <?php $form = ActiveForm::begin([
        'id' => '2fa-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}\n{hint}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-2 control-label'],
            'hintOptions' => ['class' => 'col-lg-12'],
        ],
    ]); ?>

        <p>1. <?= Yii::t('app', 'In your authentication app scan this image, or type in the following code:') ?> <b><?= $model->secret ?></b></p>
        
        <p><img src="<?= $url ?>" /></p>

        <p>2. <?= Yii::t('app', 'Finalize the process by writing the token generated by the authentication app:') ?></p>

        <?= $form->field($model, 'token')->textInput(['autofocus' => true]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton(Yii::t('app', 'Enable two-factor authentication'), ['class' => 'btn btn-primary', 'name' => '2fa-button']) ?>
            </div>

        </div>

    <?php ActiveForm::end(); ?>

</div>
